[package]
edition = "2018"
name = "notes"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "notes"

[dependencies]
serde = "1"
derive_more = "0"

hdk = {version="0.0.122", features = ["encoding"]}
